export const products = [
  {
    ImgSrc: "/img/e-catalogue-product-1.webp",
    category: "Windows",
    material: "Aluminum",
    title: "Signature Sliding Window",
    description:
      "Premium Aluminum Sliding Windows With Superior Insulation And Mode",
    rating: 4.8,
    reviews: 24,
    tags: ["Triple Glazing", "Energy Efficient"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-2.webp",
    category: "Doors",
    material: "Wood",
    title: "Classic French Doors",
    description: "Elegant French Doors Crafted From Premium Hardwood With",
    rating: 4.8,
    reviews: 24,
    tags: ["Solid Wood", "Security Glass"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-3.webp",
    category: "Folding Systems",
    material: "Aluminum",
    title: "Bi-Fold Patio System",
    description: "Innovative Bi-Fold System That Seamlessly Connects Indoor.",
    rating: 4.8,
    reviews: 24,
    tags: ["Multi-Panel", "Smooth Operation"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-4.webp",
    category: "Glass Facades",
    material: "Aluminum",
    title: "Curtain Wal Facade",
    description:
      "Commercial-Grade Curtain Wall System For Modern Architectural",
    rating: 4.8,
    reviews: 24,
    tags: ["Structural Glazing", "Thermal Break"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-5.webp",
    category: "Windows",
    material: "uPVC",
    title: "Casement Windows",
    description:
      "High-performance uPVC Casement Windows With Excellent Thermal",
    rating: 4.8,
    reviews: 24,
    tags: ["Triple Glazing", "Energy Efficient"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-6.webp",
    category: "Doors",
    material: "Composite",
    title: "Security Entry Door",
    description: "Premium Security Door With Advanced Locking Mechanism.",
    rating: 4.8,
    reviews: 24,
    tags: ["Multi-Lock System", "Impact Resistant"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-1.webp",
    category: "Windows",
    material: "Aluminum",
    title: "Signature Sliding Window",
    description:
      "Premium Aluminum Sliding Windows With Superior Insulation And Mode",
    rating: 4.8,
    reviews: 24,
    tags: ["Triple Glazing", "Energy Efficient"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-2.webp",
    category: "Doors",
    material: "Wood",
    title: "Classic French Doors",
    description: "Elegant French Doors Crafted From Premium Hardwood With",
    rating: 4.8,
    reviews: 24,
    tags: ["Solid Wood", "Security Glass"],
  },
  {
    ImgSrc: "/img/e-catalogue-product-3.webp",
    category: "Folding Systems",
    material: "Aluminum",
    title: "Bi-Fold Patio System",
    description: "Innovative Bi-Fold System That Seamlessly Connects Indoor.",
    rating: 4.8,
    reviews: 24,
    tags: ["Multi-Panel", "Smooth Operation"],
  },
];
